# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 832)
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setGeometry(QtCore.QRect(150, 20, 93, 28))
        self.searchButton.setObjectName("searchButton")
        self.searchField = QtWidgets.QLineEdit(Form)
        self.searchField.setGeometry(QtCore.QRect(20, 20, 113, 22))
        self.searchField.setObjectName("searchField")
        self.addComponentButton = QtWidgets.QPushButton(Form)
        self.addComponentButton.setGeometry(QtCore.QRect(50, 780, 151, 28))
        self.addComponentButton.setObjectName("addComponentButton")
        self.saveDatabaseButton = QtWidgets.QPushButton(Form)
        self.saveDatabaseButton.setGeometry(QtCore.QRect(270, 780, 141, 28))
        self.saveDatabaseButton.setObjectName("saveDatabaseButton")
        self.partsTable = QtWidgets.QTableWidget(Form)
        self.partsTable.setGeometry(QtCore.QRect(20, 80, 1291, 681))
        self.partsTable.setObjectName("partsTable")
        self.partsTable.setColumnCount(10)
        self.partsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.partsTable.setHorizontalHeaderItem(9, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.searchButton.setText(_translate("Form", "Search"))
        self.addComponentButton.setText(_translate("Form", "Add Component"))
        self.saveDatabaseButton.setText(_translate("Form", "Save Database"))
        item = self.partsTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.partsTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "CUS ID"))
        item = self.partsTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Type"))
        item = self.partsTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Part"))
        item = self.partsTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Description"))
        item = self.partsTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Footprint"))
        item = self.partsTable.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Stock"))
        item = self.partsTable.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Datasheet"))
        item = self.partsTable.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Delete"))
        item = self.partsTable.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Datasheet Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
